In [2]:
import pandas as pd

In [28]:
df=pd.DataFrame({   "product_id":[1,2,3,4,5,6],
        "product_name":["laptop","mobile","tv","remote","computer","mouse"],
        "price":[20000,10000,12000,100,30000,2000],
        "stock":[4,6,3,7,9,8]})

In [29]:
df

   product_id product_name  price  stock
0           1       laptop  20000      4
1           2       mobile  10000      6
2           3           tv  12000      3
3           4       remote    100      7
4           5     computer  30000      9
5           6        mouse   2000      8

In [30]:
type(df.set_index)

method

In [31]:
df.set_index("product_id")

           product_name  price  stock
product_id
1                laptop  20000      4
2                mobile  10000      6
3                    tv  12000      3
4                remote    100      7
5              computer  30000      9
6                 mouse   2000      8

In [ ]:
#using dataframes
even=df[(df["product_id"]%2==0) & (df["price"]>1000)]

In [66]:
even

   product_id product_name  price  stock
1           2       mobile  10000      6
5           6        mouse   2000      8

In [36]:
a=df["product_id"].to_numpy()
b=df["price"].to_numpy()

In [78]:
#using numpy
df[(a%2==0) & (b>1000)]

   product_id product_name  price  stock
1           2       mobile  10000      6
5           6        mouse   2000      8